apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: uit-wiki-be
  name: uit-wiki-be
spec:
  ports:
    - name: '3000'
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: uit-wiki-be
  type: NodePort
status:
  loadBalancer: {}
