apiVersion: v1
kind: Service
metadata:
  labels:
    app: document
  name: document
spec:
  ports:
    - name: '3004'
      port: 3004
      protocol: TCP
      targetPort: 3004
  selector:
    app: document
  type: ClusterIP
