services:
  chatbot:
    build:
      context: .
      dockerfile: ./apps/chatbot/Dockerfile
      target: development
    command: yarn start:dev chatbot
    env_file:
      - .env
    environment:
      - CHATBOT_API_URL=http://host.docker.internal:8000/api/v1/chat_bot/send_message
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app

  session:
    build:
      context: .
      dockerfile: ./apps/session/Dockerfile
      target: development
    command: yarn start:dev session
    env_file:
      - .env
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/src/app

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    env_file:
      - .env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app

  uit-wiki-be:
    build:
      context: .
      dockerfile: ./apps/uit-wiki-be/Dockerfile
      target: development
    depends_on:
      - session
      - chatbot
      - auth
    command: yarn start:dev uit-wiki-be
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
