apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: session
  name: session
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session
  template:
    metadata:
      labels:
        app: session
    spec:
      containers:
        - image: asia-southeast1-docker.pkg.dev/uitwiki/session/production:latest
          name: session
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: SESSION_PORT
              value: '3002'
          ports:
            - containerPort: 3002
          resources:
            requests:
              cpu: '250m'
              memory: '512Mi'
            limits:
              cpu: '500m'
              memory: '1Gi'
