apiVersion: v1
kind: Service
metadata:
  labels:
    app: session
  name: session
spec:
  ports:
    - name: '3002'
      port: 3002
      protocol: TCP
      targetPort: 3002
  selector:
    app: session
  type: ClusterIP
