apiVersion: v1
kind: Service
metadata:
  labels:
    app: chatbot
  name: chatbot
spec:
  ports:
    - name: 'tcp'
      port: 3003
      protocol: TCP
      targetPort: 3003
  selector:
    app: chatbot
  type: ClusterIP
