name: CI/CD

on:
  push:
    branches:
      - main
      - DEV
    paths-ignore:
      - 'README.md'
      - 'Dockerfile'
      # - '.github/workflows/*'
      # - 'k8s/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Config gcloud docker'
        run: 'gcloud auth configure-docker asia-southeast1-docker.pkg.dev'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push uit-wiki-be Docker image
        run: |
          docker buildx build --platform linux/amd64 -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/uit-wiki-be/production -f apps/uit-wiki-be/Dockerfile --push .

      - name: Build and push auth Docker image
        run: |
          docker buildx build --platform linux/amd64 -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/auth/production -f apps/auth/Dockerfile --push .

      - name: Build and push session Docker image
        run: |
          docker buildx build --platform linux/amd64 -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/session/production -f apps/session/Dockerfile --push .

      - name: Build and push document Docker image
        run: |
          docker buildx build --platform linux/amd64 -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/document/production -f apps/document/Dockerfile --push .

      - name: Build and push chatbot Docker image
        run: |
          docker buildx build --platform linux/amd64 -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/chatbot/production -f apps/chatbot/Dockerfile --push .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Install kubectl'
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'uit-wiki-be'
          location: 'asia-southeast1'

      - name: Deploy deployment to GKE
        run: |
          kubectl apply -f ./k8s/uit-wiki-be/templates/auth/deployment.yaml
          kubectl apply -f ./k8s/uit-wiki-be/templates/chatbot/deployment.yaml
          kubectl apply -f ./k8s/uit-wiki-be/templates/document/deployment.yaml
          kubectl apply -f ./k8s/uit-wiki-be/templates/session/deployment.yaml
          kubectl apply -f ./k8s/uit-wiki-be/templates/uit-wiki-be/deployment.yaml

      - name: Deploy service to GKE
        run: |
          kubectl apply -f ./k8s/uit-wiki-be/templates/auth/service-http.yaml
          kubectl apply -f ./k8s/uit-wiki-be/templates/auth/service-tcp.yaml
          kubectl apply -f ./k8s/uit-wiki-be/templates/chatbot/service.yaml
          kubectl apply -f ./k8s/uit-wiki-be/templates/document/service.yaml
          kubectl apply -f ./k8s/uit-wiki-be/templates/session/service.yaml
          kubectl apply -f ./k8s/uit-wiki-be/templates/uit-wiki-be/service.yaml

      - name: Apply Ingress
        run: |
          kubectl apply -f ./k8s/uit-wiki-be/templates/ingress.yaml

      - name: 'Restart and Verify Deployment'
        run: |
          kubectl rollout restart deployment auth
          kubectl rollout restart deployment chatbot
          kubectl rollout restart deployment document
          kubectl rollout restart deployment session
          kubectl rollout restart deployment uit-wiki-be
